<a href="https://colab.research.google.com/github/abkerper/project_voting/blob/main/Allison_Start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/DS3001/project_voting

Cloning into 'project_voting'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 70 (delta 5), reused 3 (delta 3), pack-reused 62
Receiving objects: 100% (70/70), 31.37 MiB | 7.50 MiB/s, done.
Resolving deltas: 100% (29/29), done.
Updating files: 100% (41/41), done.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [7]:
df1 = pd.read_csv('./project_voting/data/county_adjacencies.csv', low_memory = False)

In [8]:
df1

,County,Population2022,FIPS,District,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12
0,Accomack,33191,51001,2,Northumberland,Lancaster,Middlesex,Mathews,Northampton,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albemarle,114534,51003,5,CharlottesvilleCity,Nelson,Augusta,Rockingham,Greene,Orange,Louisa,Fluvanna,Buckingham,Nelson,NaN,NaN
2,AlexandriaCity,155525,51510,8,Fairfax,Arlington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alleghany,14835,51005,6,Craig,Bath,Botetourt,CovingtonCity,Rockbridge,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Amelia,13455,51007,5,PrinceEdward,Cumberland,Powhatan,Chesterfield,Dinwiddie,Nottoway,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,WinchesterCity,27936,51840,6,Frederick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,Wise,35421,51195,9,Lee,Scott,Dickenson,NortonCity,Russell,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,Wythe,28111,51197,9,Bland,Smyth,Grayson,Carroll,Pulaski,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,York,71341,51199,1,Gloucester,JamesCty,WilliamsburgCity,NewportNewsCity,PoquosonCity,HamptonCity,Northampton,NaN,NaN,NaN,NaN,NaN
132,WilliamsburgCity,15920,51830,1,JamesCty,York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN